package com;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.extra.Appointment;
import com.extra.Query;
import com.firebaseStuff.*;
import com.google.cloud.firestore.DocumentSnapshot;

public class Inventory {

	private static Inventory inventory = null;
	private Collection<User> listOfUsers;
	private Collection<Appointment> appointments;
	private Collection<TimeSlot> weekSchedule;
	private Collection<WorkoutExercise> availableWorkoutExercises;
	private Collection<MindfulnessExercise> availableMindfulnessExercises;
	private Collection<Query> queries;
	private ArrayList<Food> searchableFood;
	private List<String> workoutDifficulties;
	private List<String> statusList;
	private List<String> targetAttribute;
	private String currentTask;
	private FirebaseDatabase fbdb;
	private FDMEmployee currentFDMEmployee = null;
	private static DateTimeFormatter formatter = DateTimeFormatter.ISO_DATE_TIME;

	private Inventory() throws InterruptedException{
		this.fbdb = FirebaseDatabase.fbdbGetInstance();
		this.fbdb.eventTrigger();
		this.currentTask = null;
		searchableFood = new ArrayList<Food>();
	}

	public static Inventory getInstance() throws InterruptedException {
        if (inventory == null)
			inventory = new Inventory();
        return inventory;
    }

	public String getCurrentTask() {
		return this.currentTask;
	}

	public void setCurrentTask(String currentTask) {
		this.currentTask = currentTask;
	}

	public void completeTask() {
		this.fbdb.updateStartFalse(this.currentTask);
		switch(this.currentTask) {
			case "logMindfulAttempt":
				logMindfulAttempt();
				break;
			case "getMindfulHistory":
				getMindfulHistory();
				break;
			case "setupAccount":
				setupAccount();
				break;
			case "findEmail":
				findEmail();
				break;
			case "addCalories":
				addCalories();
				break;
			case "searchFood":
				searchFood();
				break;
			case "getTotalCalories":
				getTotalCalories();
				break;
			case "editCalories":
				editCalories();
				break;
			case "updateBMI":
				updateBMI();
				break;
			case "getBMI":
				getBMI();
				break;
			case "getBMIHistory":
				getBMIHistory();
				break;
			case "logout":
				logout();
				break;
			case "login":
				login();
				break;
			default:
				System.out.println("Invalid communications: "+this.currentTask);
				this.currentTask = null;
				break;
		}
	}

	private void setupAccount() {
		DocumentSnapshot document = this.fbdb.getItems("communications", "setupAccount");
		SetupAccount fdmEmployeeData = document.toObject(SetupAccount.class);
		createFDMEmployee(fdmEmployeeData.getName(), fdmEmployeeData.getUsername(), fdmEmployeeData.getEmail(),
			stringToDate(fdmEmployeeData.getDob()), fdmEmployeeData.getHeight(), fdmEmployeeData.getWeight());
		finalResponse(true);
	}

	private void login() {
		DocumentSnapshot document = this.fbdb.getItems("communications", "login");
		Login fdmEmployeeData = document.toObject(Login.class);
		DocumentSnapshot employeeDocument = this.fbdb.getItems("employees", fdmEmployeeData.getEmail());
		this.currentFDMEmployee = employeeDocument.toObject(FDMEmployee.class);
		finalResponse(true);
	}

	private void findEmail() {
		DocumentSnapshot document = this.fbdb.getItems("communications", "findEmail");
		FindEmail fdmEmployeeData = document.toObject(FindEmail.class);
		String email = this.fbdb.findEmployeeEmail(fdmEmployeeData.getUsername());
		fbdb.addToResponse("email", email);
		finalResponse(true);
	}

	private void addCalories() {
		DocumentSnapshot document = this.fbdb.getItems("communications", "addCalories");
		AddCalories calorieInfo = document.toObject(AddCalories.class);
		if (this.currentFDMEmployee != null) {
			//search database calories
			//search user calories
			//this.currentFDMEmployee.getHealthHistory().logCalories(calories, nameOfFood, weightOfFood);
		}
	}

	private void searchFood() {

	}

	private void getTotalCalories() {
		HealthHistory health = this.currentFDMEmployee.getHealthHistory();
		ArrayList<String> food = new ArrayList<String>();
		ArrayList<String> dates = new ArrayList<String>();
		ArrayList<Integer> calories = new ArrayList<Integer>();
		ArrayList<Integer> ids = new ArrayList<Integer>();
		for (Calorie calorie : health.getCalorieHistory()) {
			food.add(calorie.getFood().getName());
			dates.add(calorie.getDateLogged());
			calories.add(calorie.getCalories());
			ids.add((int)(long)calorie.getId());
		}
		String overallStats = "This is work in progress, not a priority atm";
		fbdb.addToResponse("food", food);
		fbdb.addToResponse("dates", dates);
		fbdb.addToResponse("calories", calories);
		fbdb.addToResponse("ids", ids);
		fbdb.addToResponse("overallStats", overallStats);
		finalResponse(true);
	}

	private void editCalories() {
		DocumentSnapshot document = this.fbdb.getItems("communications", "editCalories");
		EditCalories calorieInfo = document.toObject(EditCalories.class);
		if (this.currentFDMEmployee != null) {
			//TODO - search calories
		}
	}

	private void updateBMI() {
		if (this.currentFDMEmployee != null) {
			DocumentSnapshot document = this.fbdb.getItems("communications", "updateBMI");
			UpdateBMI bmiInfo = document.toObject(UpdateBMI.class);
			HealthHistory health = this.currentFDMEmployee.getHealthHistory();
			Height currentH = health.getCurrentHeight();
			Weight currentW = health.getCurrentWeight();
			if (currentH.getHeight() != bmiInfo.getHeight()) health.logHeight(bmiInfo.getHeight());
			if (currentW.getWeight() != bmiInfo.getWeight()) health.logHeight(bmiInfo.getWeight());
			updateCurrentEmployee();
		}
		finalResponse(true);
	}

	private void logMindfulAttempt() {
		DocumentSnapshot document = this.fbdb.getItems("communications", "logMindfulAttempt");
		LogMindfulAttempt logAttempt = document.toObject(LogMindfulAttempt.class);
		//DocumentSnapshot employeeDocument = this.fbdb.getItems("employees", fdmEmployeeData.getEmail());
		if (this.currentFDMEmployee != null) {
			this.currentFDMEmployee.attemptMindfulnessExercise();
			updateCurrentEmployee();
		}
		finalResponse(true);
	}

	private void getMindfulHistory() {
		
		ArrayList<MindfulnessExerciseAttempt> allattempts = this.currentFDMEmployee.getMindfulnessExerciseAttempts();
		ArrayList<Integer> attemptno = new ArrayList<Integer>();
		ArrayList<String> dates = new ArrayList<String>();
		for (MindfulnessExerciseAttempt m : allattempts){
			attemptno.add(m.getAttemptNumber());
			dates.add(m.getDateCompleted());
		}
		fbdb.addToResponse("attemptNos", attemptno);
		fbdb.addToResponse("attemptDates", dates);
		finalResponse(true);
		
	}

	private void getBMI() {

	}

	private void getBMIHistory() {

	}

	private void logout() {

	}

	private void createFDMEmployee(String nname, String userName, String email, LocalDateTime ddate, int height, int weight) {
		FDMEmployee fdmEmployee = new FDMEmployee(nname, userName, email, ddate, height, weight);
		this.currentFDMEmployee = fdmEmployee;
		updateCurrentEmployee();
	}

	private void updateCurrentEmployee() {
		this.fbdb.setItems("employees", this.currentFDMEmployee.getEmail(), this.currentFDMEmployee);
	}

	private String dateToString(LocalDateTime date) {
		return date.format(formatter);
	}

	private LocalDateTime stringToDate(String date) {
		return LocalDateTime.parse(date, formatter);
	}

	private void finalResponse(boolean confirm) {
		this.fbdb.addToResponse("task", this.currentTask);
		this.fbdb.addToResponse("confirmation", confirm);
		this.fbdb.sendResponse();
		this.currentTask = null;
	}

	private void addNewFood(String name, int calories) {
		Food tempFood = new Food();
		tempFood.setCaloriesPer100g(calories);
		tempFood.setName(name);
		tempFood.setWeight(100);
		this.searchableFood.add(tempFood);
	}

	public void addManyFood() {
		Map<String, Integer> map = new HashMap<String, Integer>(){{
			put("1000 Island Dressing", 370);
			put("3 Musketeers", 400);
			put("7up", 44);
			put("ACE Drink", 44);
			put("Absinthe", 348);
			put("Acai Juice", 58);
			put("Acai", 70);
			put("Acerola", 32);
			put("Acorn", 387);
			put("Activia Lemon", 100);
			put("Activia Strawberry", 97);
			put("Activia", 74);
			put("Advocaat", 283);
			put("After Eight", 452);
			put("Agar-Agar", 26);
			put("Agave Syrup", 310);
			put("Airheads", 375);
			put("Ajvar", 18);
			put("Ale", 35);
			put("Alfalfa Sprouts", 23);
			put("All Purpose Flour", 364);
			put("All-blue Potatoes", 61);
			put("Alligator Meat", 232);
			put("Alligator", 104);
			put("Alligator", 232);
			put("Almond Butter", 614);
			put("Almond Extract", 258);
			put("Almond Extract", 374);
			put("Almond Milk", 17);
			put("Almond Oil", 882);
			put("Almond Oil", 882);
			put("Almond Roca", 571);
			put("Almonds", 529);
			put("Almonds", 575);
			put("Aloe Vera Yogurt", 85);
			put("Aloe Vera", 44);
			put("Alphabet Soup", 25);
			put("Altbier", 43);
			put("Amaranth", 371);
			put("Amaretto", 310);
			put("American Cheese", 148);
			put("American Cheese", 148);
			put("Anchovy", 131);
			put("Andouille", 232);
			put("Angel Delight", 451);
			put("Angel Food Cake", 258);
			put("Animal Crackers", 446);
			put("Anise Seed", 337);
			put("Anise", 337);
			put("Antelope Meat", 150);
			put("Apple Butter", 173);
			put("Apple Cake", 252);
			put("Apple Cobbler", 198);
			put("Apple Crisp", 156);
			put("Apple Crumble", 156);
			put("Apple Juice", 46);
			put("Apple Pie Filling", 100);
			put("Apple Pie", 237);
			put("Apple Pie", 237);
			put("Apple Spritzer", 24);
			put("Apple Strudel", 274);
			put("Apple Turnover", 348);
			put("Apple Turnover", 348);
			put("Apple", 52);
			put("Applejack", 233);
			put("Applesauce Cake", 358);
			put("Applesauce", 62);
			put("Applesauce", 68);
			put("Applesauce", 68);
			put("Applewood", 410);
			put("Applewood", 410);
			put("Apricot Jam", 250);
			put("Apricot Kernel Oil", 889);
			put("Apricot Nectar", 56);
			put("Apricot", 48);
			put("Arby’s Grand Turkey Club", 210);
			put("Arby’s Reuben", 208);
			put("Arby’s Roast Beef Classic", 234);
			put("Arby’s Roast Beef Max", 234);
			put("Argan Oil", 896);
			put("Arrabiata Sauce", 36);
			put("Arrowroot", 65);
			put("Artichoke", 47);
			put("Arugula", 25);
			put("Arugula", 25);
			put("Asiago Cheese", 392);
			put("Asian Pear", 42);
			put("Asparagus", 20);
			put("Asti", 138);
			put("Aubergine", 25);
			put("Avocado Oil", 857);
			put("Avocado Oil", 857);
			put("Avocado", 160);
			put("Avocado", 160);
			put("Ayran", 42);
			put("Azuki Bean", 124);
			put("BBQ Chicken Pizza", 234);
			put("BBQ Pizza", 224);
			put("BBQ Rib", 212);
			put("BBQ Ribs", 255);
			put("BLT", 247);
			put("Babassu Oil", 884);
			put("Baby Back Ribs", 259);
			put("Baby Ruth", 469);
			put("Babybel", 333);
			put("Bacon and Eggs", 252);
			put("Bacon", 407);
			put("Bacon", 407);
			put("Bagel", 257);
			put("Baguette", 274);
			put("Baileys", 327);
			put("Bailey’s Irish Cream", 327);
			put("Baked Alaska", 247);
			put("Baked Beans", 94);
			put("Baked Chicken", 164);
			put("Baked Ham", 343);
			put("Baked Potato", 93);
			put("Bakewell Tart", 430);
			put("Baking Powder", 53);
			put("Baking Soda", 0);
			put("Balsamic Vinaigrette Dressing", 290);
			put("Balsamic Vinegar", 88);
			put("Bamboo Shoots", 27);
			put("Banana Bread", 326);
			put("Banana Juice", 50);
			put("Banana Nut Bread", 326);
			put("Banana", 89);
			put("Banana", 89);
			put("Banoffee Pie", 395);
			put("Barbecue Sauce", 150);
			put("Barley Groats", 100);
			put("Barley", 354);
			put("Barq’s", 46);
			put("Basil", 233);
			put("Baskin-Robbins", 239);
			put("Bass", 45);
			put("Bean Burrito", 200);
			put("Bean Curd", 76);
			put("Bean Sprouts", 30);
			put("Bean Stew", 133);
			put("Bear Meat", 259);
			put("Beaver Meat", 212);
			put("Bechamel Sauce", 225);
			put("Beck’s", 39);
			put("Beechnut", 576);
			put("Beef Bouillon", 3);
			put("Beef Brain", 196);
			put("Beef Brisket", 137);
			put("Beef Brisket", 242);
			put("Beef Fillet", 189);
			put("Beef Goulash", 123);
			put("Beef Heart", 165);
			put("Beef Jerky", 410);
			put("Beef Kidney", 158);
			put("Beef Liver", 191);
			put("Beef Lung", 120);
			put("Beef Melt", 271);
			put("Beef Minute Steak", 133);
			put("Beef Neck", 213);
			put("Beef Noodle Soup", 34);
			put("Beef Pancreas", 271);
			put("Beef Patty", 247);
			put("Beef Pizza", 304);
			put("Beef Prime Rib", 404);
			put("Beef Ribs", 196);
			put("Beef Ribs", 238);
			put("Beef Salami", 375);
			put("Beef Sirloin", 182);
			put("Beef Soup", 33);
			put("Beef Stew", 95);
			put("Beef Suet", 854);
			put("Beef Tallow", 902);
			put("Beef Tenderloin", 218);
			put("Beef Thymus", 319);
			put("Beef Tongue", 284);
			put("Beef Tripe", 94);
			put("Beef", 171);
			put("Beef", 248);
			put("Beer Bread", 227);
			put("Beer", 43);
			put("Beer", 43);
			put("Beetroot", 43);
			put("Bell Pepper", 20);
			put("Ben and Jerry’s", 228);
			put("Bengal Gram", 364);
			put("Bergkäse", 418);
			put("Bernaise Sauce", 414);
			put("Bianca Pizza", 246);
			put("Big N’ Tasty", 223);
			put("Bircher Muesli Yogurt", 109);
			put("Birthday Cake", 465);
			put("Biryani", 176);
			put("Biscuit", 269);
			put("Bison Meat", 171);
			put("Bison Sirloin", 171);
			put("Bison", 171);
			put("Bitter Lemon", 34);
			put("Black Beans", 341);
			put("Black Bread", 250);
			put("Black Chickpeas", 364);
			put("Black Forest Cake", 264);
			put("Black Gram", 341);
			put("Black Olives", 115);
			put("Black Pepper", 251);
			put("Black Pudding", 253);
			put("Black Pudding", 379);
			put("Black Rice", 323);
			put("Black Sesame Seeds", 573);
			put("Black and White Cookie", 381);
			put("Blackberries", 43);
			put("Blackberry Jam", 250);
			put("Blackberry Juice", 48);
			put("Blackcurrant Jam", 250);
			put("Blood Oranges", 50);
			put("Blood Sausage", 379);
			put("Blue Cheese Dressing", 533);
			put("Blue Cheese", 353);
			put("Blue Curacao", 243);
			put("Blue Moon", 48);
			put("Blueberries", 57);
			put("Blueberry Cobbler", 234);
			put("Blueberry Jam", 250);
			put("Blueberry Muffin", 377);
			put("Blueberry Pie", 232);
			put("Blueberry Yogurt", 105);
			put("Bluefish", 159);
			put("Bock Beer", 50);
			put("Bockwurst", 301);
			put("Boiled Ham", 104);
			put("Boiled Ham", 126);
			put("Boiled Potatoes", 87);
			put("Bologna", 247);
			put("Bologna", 247);
			put("Bolognese", 106);
			put("Boudin", 194);
			put("Bouillon", 16);
			put("Bourbon", 233);
			put("Boysenberry Juice", 54);
			put("Bran Flakes", 356);
			put("Bran Muffins", 270);
			put("Brandy", 213);
			put("Bratwurst", 297);
			put("Bratwurst", 333);
			put("Brawn", 157);
			put("Brawn", 309);
			put("Brazil Nuts", 656);
			put("Bread Flour", 361);
			put("Bread Pudding", 153);
			put("Breadfruit", 103);
			put("Breadfruit", 191);
			put("Breadsticks", 400);
			put("Breakfast Sausage Links", 339);
			put("Bream", 135);
			put("Bresaola", 178);
			put("Brie", 334);
			put("Brioche", 346);
			put("Brittle", 592);
			put("Broccoli Cheese Soup", 87);
			put("Broccoli Soup", 87);
			put("Broccoli", 34);
			put("Broth", 100);
			put("Brown Bread", 246);
			put("Brown Lentil", 353);
			put("Brown Rice", 362);
			put("Brown Rice", 388);
			put("Brown Sugar", 395);
			put("Brownies", 405);
			put("Brussels Sprouts", 43);
			put("Buckler (N.A.)", 21);
			put("Buckwheat Groats", 346);
			put("Buckwheat", 343);
			put("Bud Ice", 35);
			put("Bud Light Chelada", 43);
			put("Bud Light Lime", 34);
			put("Bud Light", 29);
			put("Bud Select 55", 15);
			put("Bud Select", 28);
			put("Budweiser Chelada", 52);
			put("Budweiser", 41);
			put("Buffalo Chicken Pizza", 252);
			put("Buffalo Meat", 131);
			put("Buffalo", 131);
			put("Bun", 316);
			put("Bundt Cake", 370);
			put("Burger King Angry Whopper", 255);
			put("Burger King Double Whopper with Cheese", 249);
			put("Burger King Double Whopper", 239);
			put("Burger King Original Chicken Sandwich", 301);
			put("Burger King Premium Alaskan Fish Sandwich", 259);
			put("Burger King Triple Whopper", 269);
			put("Burger King Whopper Jr.", 234);
			put("Burger King Whopper with Cheese", 241);
			put("Burger King Whopper", 231);
			put("Burrito", 163);
			put("Busch Light", 27);
			put("Busch N.A.", 17);
			put("Busch", 37);
			put("Butter Cheese", 388);
			put("Butter Chicken", 140);
			put("Butter Pecan Ice Cream", 248);
			put("Butter", 720);
			put("Butterfinger", 450);
			put("Butterfish", 187);
			put("Buttermilk Pancakes", 238);
			put("Buttermilk Pie", 380);
			put("Buttermilk Ranch Dressing", 533);
			put("Buttermilk", 62);
			put("Buttermilk", 62);
			put("Butternut", 612);
			put("Butternut", 612);
			put("Butterscotch Chips", 539);
			put("Cabbage Soup", 28);
			put("Cabbage", 25);
			put("Cabernet Sauvignon", 77);
			put("Caesar Dressing", 429);
			put("Cake Flour", 362);
			put("Calabrese Pizza", 235);
			put("Calamari", 175);
			put("Calf Brain", 136);
			put("Calf Liver", 192);
			put("Calf Lung", 104);
			put("Calf Melt", 256);
			put("California Roll", 93);
			put("Calzone", 231);
			put("Camembert", 300);
			put("Canada Dry Ginger Ale", 41);
			put("Canadian Whiskey", 216);
			put("Canadian-Style Bacon", 107);
			put("Candied Orange Peel", 97);
			put("Candy Apple", 152);
			put("Candy Cane", 423);
			put("Candy Corn", 360);
			put("Candy Floss", 400);
			put("Candy canes", 423);
			put("Cane Sugar", 387);
			put("Canned Apricots", 48);
			put("Canned Blackberries", 92);
			put("Canned Blueberries", 88);
			put("Canned Cherries", 54);
			put("Canned Cranberries", 178);
			put("Canned Crushed Pineapple", 53);
			put("Canned Figs", 107);
			put("Canned Fruit Cocktail", 81);
			put("Canned Fruit Salad", 50);
			put("Canned Gooseberries", 73);
			put("Canned Grapefruit", 37);
			put("Canned Grapes", 76);
			put("Canned Mandarin Oranges", 71);
			put("Canned Mango", 65);
			put("Canned Mangosteen", 73);
			put("Canned Mixed Fruit", 71);
			put("Canned Morello Cherries", 81);
			put("Canned Oranges", 62);
			put("Canned Peaches", 54);
			put("Canned Pears", 35);
			put("Canned Pineapple", 60);
			put("Canned Plums", 58);
			put("Canned Raspberries", 91);
			put("Canned Sliced Pineapple", 53);
			put("Canned Sour Cherries", 114);
			put("Canned Strawberries", 92);
			put("Canned Tangerines", 61);
			put("Cannelloni", 146);
			put("Cannoli", 254);
			put("Canola Oil", 884);
			put("Canola Oil", 884);
			put("Cantaloupe Melon", 34);
			put("Cantaloupe", 34);
			put("Capellini", 353);
			put("Capers", 23);
			put("Capicola", 110);
			put("Capon", 229);
			put("Cappelletti", 164);
			put("Capri-Sun", 41);
			put("Capricciosa Pizza", 260);
			put("Capsicum", 27);
			put("Cap’n Crunch", 404);
			put("Caramel Cake", 385);
			put("Caramel Cake", 475);
			put("Caramel Popcorn", 376);
			put("Caramel squares", 367);
			put("Caraway Seeds", 333);
			put("Cardamom", 311);
			put("Caribou", 159);
			put("Carlsberg", 32);
			put("Carp", 162);
			put("Carrot Cake", 408);
			put("Carrot Ginger Soup", 25);
			put("Carrot Juice", 40);
			put("Carrot Soup", 25);
			put("Carrot", 41);
			put("Carvel", 212);
			put("Casaba Melon", 28);
			put("Cashew", 553);
			put("Cassava", 160);
			put("Cassava", 160);
			put("Catalina Dressing", 282);
			put("Cauliflower", 25);
			put("Cava", 76);
			put("Caviar", 264);
			put("Cayenne Pepper", 318);
			put("Celebrations", 490);
			put("Celery", 16);
			put("Cellophane Noodles", 351);
			put("Chai Tea", 0);
			put("Chai", 0);
			put("Challah", 283);
			put("Chambord", 348);
			put("Chamomile Tea", 0);
			put("Champagne", 75);
			put("Champagne", 76);
			put("Chapati", 240);
			put("Chard", 19);
			put("Chard", 19);
			put("Chardonnay", 85);
			put("Chasseur Sauce", 45);
			put("Cheddar", 403);
			put("Cheddar", 403);
			put("Cheerios", 347);
			put("Cheese Fondue", 228);
			put("Cheese Pastry", 374);
			put("Cheese Pizza", 267);
			put("Cheese Platter", 357);
			put("Cheese Slices", 356);
			put("Cheese Spread", 290);
			put("Cheese Spread", 290);
			put("Cheese Tortellini", 291);
			put("Cheese Whiz", 276);
			put("Cheeseburger", 263);
			put("Cheesecake", 321);
			put("Cheez-It’s", 533);
			put("Chenin Blanc", 80);
			put("Cherimoya", 75);
			put("Cherries", 50);
			put("Cherry Coke", 44);
			put("Cherry Jam", 250);
			put("Cherry Juice", 45);
			put("Cherry Pie", 260);
			put("Cherry Tomato", 100);
			put("Cherry Yogurt", 97);
			put("Chess Pie", 411);
			put("Chester", 387);
			put("Chestnut", 213);
			put("Chex", 387);
			put("Chia Seeds", 486);
			put("Chicken Bouillon", 4);
			put("Chicken Breast Fillet", 79);
			put("Chicken Breast", 163);
			put("Chicken Breast", 172);
			put("Chicken Breast", 172);
			put("Chicken Breast", 79);
			put("Chicken Broth", 16);
			put("Chicken Caesar Salad", 127);
			put("Chicken Drumstick", 185);
			put("Chicken Drumsticks", 185);
			put("Chicken Fajita", 147);
			put("Chicken Fat", 898);
			put("Chicken Fried Steak", 151);
			put("Chicken Giblets", 158);
			put("Chicken Giblets", 277);
			put("Chicken Gizzards", 146);
			put("Chicken Gizzards", 154);
			put("Chicken Gumbo Soup", 23);
			put("Chicken Heart", 185);
			put("Chicken Leg", 174);
			put("Chicken Legs", 174);
			put("Chicken Liver", 167);
			put("Chicken Liver", 172);
			put("Chicken Marsala", 96);
			put("Chicken McNuggets", 302);
			put("Chicken Meat", 172);
			put("Chicken Meat", 79);
			put("Chicken Noodle Soup", 25);
			put("Chicken Nuggets", 296);
			put("Chicken Parmesan", 110);
			put("Chicken Pizza", 234);
			put("Chicken Pizziola", 141);
			put("Chicken Pot Pie", 223);
			put("Chicken Salad", 81);
			put("Chicken Sandwich", 241);
			put("Chicken Stock", 16);
			put("Chicken Stomach", 148);
			put("Chicken Teriyaki Sandwich", 138);
			put("Chicken Thigh", 229);
			put("Chicken Thighs", 229);
			put("Chicken Tikka Masala", 81);
			put("Chicken Vegetable Soup", 31);
			put("Chicken Wing", 266);
			put("Chicken Wings", 266);
			put("Chicken Wings", 324);
			put("Chicken with Rice Soup", 24);
			put("Chicken", 219);
			put("Chicken", 219);
			put("Chickpeas", 364);
			put("Chicory Greens", 23);
			put("Chicory Roots", 72);
			put("Chicory", 72);
			put("Chili Bean", 97);
			put("Chili Powder", 282);
			put("Chili Sauce", 112);
			put("Chili con Carne", 105);
			put("Chili", 282);
			put("Chimichanga", 232);
			put("Chinese Cabbage", 16);
			put("Chitterlings", 233);
			put("Chitterlings", 233);
			put("Chive Cream Cheese", 342);
			put("Chives", 30);
			put("Chives", 30);
			put("Chocolate Bar", 533);
			put("Chocolate Cake", 389);
			put("Chocolate Cheerios", 367);
			put("Chocolate Chip Ice Cream", 215);
			put("Chocolate Chips", 467);
			put("Chocolate Chips", 493);
			put("Chocolate Cream Pie", 304);
			put("Chocolate Ice Cream", 216);
			put("Chocolate Milk", 89);
			put("Chocolate Milkshake", 125);
			put("Chocolate Mousse Cake", 260);
			put("Chocolate Mousse Pie", 260);
			put("Chocolate Mousse", 225);
			put("Chocolate Muffin", 420);
			put("Chocolate Philadelphia", 287);
			put("Chocolate Spread", 541);
			put("Chocolate Sprinkles", 500);
			put("Chocolate Wine", 256);
			put("Chocolate Yogurt", 128);
			put("Chocolate", 529);
			put("Chocos", 380);
			put("Chop Suey", 172);
			put("Chopped Ham", 180);
			put("Chorizo", 455);
			put("Chorizo", 455);
			put("Chuck Roast", 141);
			put("Chuck Steak", 137);
			put("Chuck Steak", 277);
			put("Ciabatta", 271);
			put("Ciao Bella", 109);
			put("Cider Vinegar", 21);
			put("Cider", 49);
			put("Cilantro", 23);
			put("Cinnamon Bun", 436);
			put("Cinnamon Toast Crunch", 433);
			put("Cinnamon", 247);
			put("Clam", 148);
			put("Clamato", 60);
			put("Clausthaler (N.A.)", 26);
			put("Clementine", 47);
			put("Cloves", 274);
			put("Club Mate", 30);
			put("Cobb Salad", 118);
			put("Coca Cola", 42);
			put("Coco Pops", 376);
			put("Cocoa Krispies", 386);
			put("Cocoa Pebbles", 367);
			put("Cocoa Powder", 228);
			put("Cocoa Puffs", 400);
			put("Coconut Cake", 356);
			put("Coconut Flakes", 456);
			put("Coconut Milk", 230);
			put("Coconut Milk", 233);
			put("Coconut Milk", 50);
			put("Coconut Oil", 857);
			put("Coconut Oil", 857);
			put("Coconut Water", 19);
			put("Coconut", 354);
			put("Cod Liver Oil", 1000);
			put("Cod", 105);
			put("Coffee Cake", 331);
			put("Coffee Cake", 418);
			put("Coffee Creamer", 195);
			put("Coffee Ice Cream", 236);
			put("Coffee", 1);
			put("Cognac", 235);
			put("Cointreau", 320);
			put("Coke Zero", 0);
			put("Coke Zero", 1);
			put("Coke", 42);
			put("Cola", 42);
			put("Colby Cheese", 394);
			put("Colby Cheese", 394);
			put("Colby-Jack Cheese", 394);
			put("Colby-Jack Cheese", 394);
			put("Cold Pack Cheese", 246);
			put("Cold Stone Creamery", 232);
			put("Collard Greens", 28);
			put("Collard Greens", 32);
			put("Colt 45", 44);
			put("Conchas/Mexican Sweet Bread", 353);
			put("Concord Grape", 71);
			put("Condensed Milk", 321);
			put("Cooked Ham", 133);
			put("Cookie Crisp", 400);
			put("Cookie Dough Ice Cream", 200);
			put("Cookies", 488);
			put("Coors Light", 29);
			put("Coors N.A.", 18);
			put("Coors", 42);
			put("Coriander", 23);
			put("Corn Dog", 250);
			put("Corn Flakes", 357);
			put("Corn Flour", 361);
			put("Corn Oil", 800);
			put("Corn Oil", 800);
			put("Corn Pops", 377);
			put("Corn Syrup", 281);
			put("Corn Waffles", 274);
			put("Corn", 365);
			put("Cornbread", 179);
			put("Corned Beef Hash", 164);
			put("Corned Beef", 153);
			put("Corned Beef", 251);
			put("Cornish Hens", 259);
			put("Cornmeal", 362);
			put("Cornmeal", 362);
			put("Cornstarch", 381);
			put("Cornstarch", 381);
			put("Corona", 42);
			put("Cottage Cheese", 98);
			put("Cottage Cheese", 98);
			put("Cottage Cheese", 98);
			put("Cottage Pie", 139);
			put("Cotton Candy", 643);
			put("Cotton Seeds", 506);
			put("Cottonseed Oil", 882);
			put("Cottonseed Oil", 882);
			put("Count Chocula", 407);
			put("Courgette", 17);
			put("Couscous", 376);
			put("Couverture", 600);
			put("Cracker", 502);
			put("Cracklin Oat Bran", 402);
			put("Cranberries", 46);
			put("Cranberry Apple Juice", 67);
			put("Cranberry Grape Juice", 71);
			put("Cranberry Juice", 46);
			put("Crawfish", 82);
			put("Crayfish", 87);
			put("Cream Cheese with Herbs", 342);
			put("Cream Cheese", 342);
			put("Cream Cheese", 342);
			put("Cream Cheese", 54);
			put("Cream Puff", 334);
			put("Cream Sauce", 180);
			put("Cream Yogurt", 124);
			put("Cream of Asparagus Soup", 35);
			put("Cream of Broccoli Soup", 45);
			put("Cream of Celery Soup", 37);
			put("Cream of Chicken Soup", 48);
			put("Cream of Mushroom Soup", 39);
			put("Cream of Onion Soup", 44);
			put("Cream of Potato Soup", 30);
			put("Cream of Tartar", 258);
			put("Cream of Tartar", 258);
			put("Cream of Wheat", 364);
			put("Cream", 242);
			put("Creamed Spinach", 74);
			put("Creamy Chicken Noodle Soup", 23);
			put("Creamy Yogurt", 90);
			put("Creme Fraiche", 393);
			put("Crepes", 224);
			put("Cress", 32);
			put("Croissant", 406);
			put("Croquettes", 127);
			put("Crumb Cake", 441);
			put("Crumpet", 178);
			put("Crunchie McFlurry", 174);
			put("Crunchy Nut Cornflakes", 600);
			put("Crunchy Nut", 600);
			put("Crystal Light", 263);
			put("Crystallized Ginger", 335);
			put("Crystallized Ginger", 335);
			put("Cubed Steak", 199);
			put("Cucumber Juice", 10);
			put("Cucumber", 16);
			put("Cumberland Sausage", 250);
			put("Cumin Seed", 375);
			put("Cumin", 375);
			put("Cupcake", 305);
			put("Cupcakes", 305);
			put("Curd", 98);
			put("Curly Fries", 311);
			put("Currant Juice", 48);
			put("Currants", 56);
			put("Curry Ketchup", 124);
			put("Curry Sauce", 26);
			put("Curry", 325);
			put("Custard Apple", 101);
			put("Custard Powder", 337);
			put("Custard", 122);
			put("Dairy Milk McFlurry", 186);
			put("Dal", 230);
			put("Dal", 330);
			put("Dampfnudel", 274);
			put("Dandelion", 45);
			put("Danish Pastry", 374);
			put("Dark Beer", 46);
			put("Dark Rum", 216);
			put("Dates", 282);
			put("Deep Dish Pizza", 265);
			put("Deep-Fried Tofu", 271);
			put("Deviled Eggs", 201);
			put("Dextrose", 375);
			put("Diet Cherry Coke", 1);
			put("Diet Coke", 1);
			put("Diet Coke", 1);
			put("Diet Dr. Pepper", 0);
			put("Diet Pepsi", 0);
			put("Diet Sunkist", 0);
			put("Diet Yogurt", 54);
			put("Dill Weed", 43);
			put("Dill", 43);
			put("Dim Sum", 193);
			put("Dippin Dots", 224);
			put("Dominos Philly Cheese Steak Pizza", 224);
			put("Donut", 403);
			put("Donut/Doughnut", 421);
			put("Dosa", 209);
			put("Dosa", 66);
			put("Double Cheeseburger", 267);
			put("Double Rainbow", 257);
			put("Doughnut", 403);
			put("Dove", 213);
			put("Dr. Brown’s", 53);
			put("Dr. Pepper", 27);
			put("Dragon Fruit", 60);
			put("Drambuie", 358);
			put("Dried Apricots", 241);
			put("Dried Cranberries", 308);
			put("Dried Figs", 249);
			put("Dried Fruit", 243);
			put("Dried Prunes", 107);
			put("Drumsticks", 255);
			put("Dry Red Wine", 85);
			put("Duck Breast", 201);
			put("Duck Egg", 185);
			put("Duck Liver", 136);
			put("Duck", 337);
			put("Duck", 337);
			put("Dumpling Dough", 124);
			put("Dumpling Dough", 99);
			put("Dumplings", 124);
			put("Durian", 147);
			put("Durum Wheat Semolina", 397);
			put("Durum Wheat Semolina", 397);
			put("Dutch Cheese", 393);
			put("Dutch Loaf", 268);
			put("Edam Cheese", 357);
			put("Edam Cheese", 357);
			put("Edam", 357);
			put("Eel", 236);
			put("Egg Cream", 94);
			put("Egg Nog", 88);
			put("Egg Nog", 88);
			put("Egg Noodles", 384);
			put("Egg Roll", 250);
			put("Egg White", 13);
			put("Egg Yolk", 322);
			put("Egg", 97);
			put("Egg", 97);
			put("Eggplant", 25);
			put("Eggy Bread", 196);
			put("Elderflower Cordial", 29);
			put("Emmental", 357);
			put("Emmentaler", 357);
			put("Emmentaler", 357);
			put("Empanada", 335);
			put("Emu", 152);
			put("Enchiladas", 168);
			put("Endive", 17);
			put("Energy-Drink", 87);
			put("English Muffin", 227);
			put("Esrom (Cheese)", 322);
			put("Evaporated Milk", 134);
			put("Evaporated Milk", 135);
			put("Evian", 0);
			put("Extra-Firm Tofu", 91);
			put("Fairy Cakes", 440);
			put("Fajita", 117);
			put("Falafel", 335);
			put("Fanta Zero", 0);
			put("Fanta", 39);
			put("Farfalle", 358);
			put("Feijoa", 55);
			put("Fennel Seed", 345);
			put("Fennel", 31);
			put("Fennel", 31);
			put("Fenugreek", 323);
			put("Ferrero Rocher", 576);
			put("Feta Cream Cheese", 342);
			put("Feta", 264);
			put("Fettuccine", 353);
			put("Fiber One", 267);
			put("Figs", 74);
			put("Filet Mignon", 207);
			put("Filet Mignon", 267);
			put("Filet-o-Fish", 282);
			put("Firm Tofu", 70);
			put("Fish Fingers", 290);
			put("Fish Sandwich", 273);
			put("Fish Sticks", 290);
			put("Fish and Chips", 195);
			put("Fish and Chips", 195);
			put("Five Alive", 35);
			put("Flageolet", 85);
			put("Flan", 145);
			put("Flank Steak", 194);
			put("Flank Steak", 194);
			put("Flapjack", 486);
			put("Flat Iron Steak", 137);
			put("Flatbread", 311);
			put("Flaxseed Oil", 884);
			put("Flaxseed Oil", 884);
			put("Flaxseed", 534);
			put("Flaxseed", 534);
			put("Flounder", 86);
			put("Flour", 364);
			put("Flourless Chocolate Cake", 509);
			put("Focaccia", 249);
			put("Fol Epi", 388);
			put("Fontina", 389);
			put("Fortune Cookies", 214);
			put("Four Cheese Pizza", 221);
			put("Frangelico", 238);
			put("Frankfurters", 305);
			put("Freekeh", 520);
			put("French Cruller", 412);
			put("French Dressing", 60);
			put("French Fingerling Potatoes", 82);
			put("French Fries", 312);
			put("French Fries", 312);
			put("French Onion Soup", 23);
			put("French Vanilla Ice Cream", 201);
			put("Fresca", 0);
			put("Fresh Mozzarella", 280);
			put("Fresh Mozzarella", 280);
			put("Fried Bean Curd", 271);
			put("Fried Potatoes", 312);
			put("Fried Rice", 186);
			put("Fried Shrimp", 277);
			put("Friendly’s", 212);
			put("Froot Loops", 379);
			put("Frosted Cheerios", 393);
			put("Frosted Flakes", 367);
			put("Frosted Mini-Wheats", 353);
			put("Frosties", 367);
			put("Fructose", 368);
			put("Fruit Cake", 324);
			put("Fruit Yogurt", 97);
			put("Fruit salad", 50);
			put("Fruitopia", 110);
			put("Fruity Pebbles", 400);
			put("Full Throttle", 110);
			put("Funnel Cake", 307);
			put("Fusilli", 352);
			put("Fuze Tea", 25);
			put("Fuze", 20);
			put("Galia Melon", 23);
			put("Gamay", 78);
			put("Garlic Bread", 350);
			put("Garlic Cream Cheese", 342);
			put("Garlic Powder", 331);
			put("Garlic Salt", 0);
			put("Garlic Sausage", 169);
			put("Garlic", 149);
			put("Garlic", 149);
			put("Gatorade", 23);
			put("Gatorade", 25);
			put("Gelatin", 335);
			put("Genesee Cream Ale", 46);
			put("German Chocolate Cake", 370);
			put("Ghee", 120);
			put("Gherkin", 14);
			put("Gin", 263);
			put("Ginger Ale", 35);
			put("Ginger Beer", 42);
			put("Ginger Tea", 0);
			put("Ginger", 80);
			put("Gingerbread", 356);
			put("Ginkgo Nuts", 182);
			put("Gjetost", 466);
			put("Glass Noodles", 192);
			put("Glenfiddich", 230);
			put("Glucose Syrup", 387);
			put("Glucose", 286);
			put("Gluten", 370);
			put("Gnocchi", 133);
			put("Goa Bean", 409);
			put("Goat Cheese Pizza", 219);
			put("Goat Cheese", 364);
			put("Goat Cheese", 364);
			put("Goat Milk", 69);
			put("Golden Grahams", 400);
			put("Golden Mushroom Soup", 65);
			put("Goose Fat", 898);
			put("Goose Liver", 133);
			put("Goose Meat", 238);
			put("Goose", 238);
			put("Goose", 305);
			put("Gorgonzola", 350);
			put("Gouda Cheese", 356);
			put("Gouda", 356);
			put("Gouda", 356);
			put("Goulash", 1009);
			put("Gourd", 14);
			put("Grand Marnier", 253);
			put("Granola Bars", 452);
			put("Granulated Sugar", 387);
			put("Grape Jelly", 255);
			put("Grape Juice", 60);
			put("Grape Leaves", 93);
			put("Grape Seed Oil", 884);
			put("Grape Seed Oil", 884);
			put("Grape-Nuts", 362);
			put("Grapefruit Juice", 46);
			put("Grapefruit", 42);
			put("Grapes", 69);
			put("Grated Parmesan", 431);
			put("Gravy", 53);
			put("Greek Dressing", 467);
			put("Greek Yogurt", 53);
			put("Green Beans", 31);
			put("Green Beans", 31);
			put("Green Gram", 347);
			put("Green Lentil", 257);
			put("Green Olives", 115);
			put("Green Onion", 32);
			put("Greengage", 41);
			put("Grilled Cheese Sandwich", 288);
			put("Grilled Cheese", 350);
			put("Grilled Chicken Salad", 88);
			put("Grilled Pizza", 226);
			put("Grissini", 408);
			put("Ground Beef", 241);
			put("Ground Beef", 246);
			put("Ground Chuck", 250);
			put("Ground Cinnamon", 247);
			put("Ground Ginger", 335);
			put("Ground Pork", 263);
			put("Ground Round", 212);
			put("Ground Round", 246);
			put("Grouper", 118);
			put("Gruyere", 413);
			put("Guava", 68);
			put("Guava", 68);
			put("Guinea-Fowl", 158);
			put("Guinness", 35);
			put("Gumdrops", 321);
			put("Gummi Bears", 316);
			put("Haddock", 90);
			put("Hake", 71);
			put("Halibut", 111);
			put("Halloumi", 321);
			put("Ham Sandwich", 241);
			put("Ham Sausage", 164);
			put("Ham and Cheese Sandwich", 241);
			put("Ham", 145);
			put("Ham", 163);
			put("Hamburger Sauce", 383);
			put("Hamburger", 254);
			put("Hanuta", 541);
			put("Harissa", 52);
			put("Havarti", 371);
			put("Havarti", 371);
			put("Hawaiian Pizza", 115);
			put("Hawaiian Punch", 31);
			put("Hazelnut Oil", 889);
			put("Hazelnut", 628);
			put("Hazelnuts", 628);
			put("Head Cheese", 157);
			put("Healthy Choice", 125);
			put("Heavy Cream", 345);
			put("Heineken", 35);
			put("Hemp Oil", 807);
			put("Herring Oil", 902);
			put("Herring", 203);
			put("Hershey Kisses", 471);
			put("Hi-C", 49);
			put("Hickory Ham", 188);
			put("Hickory Nuts", 657);
			put("Hog Maws", 157);
			put("Hog Maws", 250);
			put("Hoki", 121);
			put("Hollandaise Sauce", 535);
			put("Honey Brown", 42);
			put("Honey Ham", 122);
			put("Honey Mustard Dressing", 464);
			put("Honey Nut Cheerios", 393);
			put("Honey Smacks", 370);
			put("Honey", 304);
			put("Honeycomb", 397);
			put("Honeydew", 36);
			put("Horchata", 54);
			put("Horseradish", 48);
			put("Horseradish", 48);
			put("Horseradish", 48);
			put("Horseradish", 48);
			put("Hot Chocolate", 89);
			put("Hot Chocolate", 89);
			put("Hot Dog Buns", 279);
			put("Hot Dog", 269);
			put("Hot Dogs", 278);
			put("Hot Fudge Sundae", 186);
			put("Hot Pepper", 318);
			put("Hot Sausage", 259);
			put("Hummus", 177);
			put("Hurricane High Gravity", 39);
			put("I can’t believe it’s not Butter", 357);
			put("IPA", 51);
			put("Ice Cream Cake", 200);
			put("Ice Cream Sandwich", 237);
			put("Ice Cream Sundae", 142);
			put("Ice Milk", 159);
			put("Ice Tea", 27);
			put("Ice Tea", 27);
			put("Iced Tea", 27);
			put("Instant Ramen", 436);
			put("Iodized Salt", 0);
			put("Irish Whiskey", 233);
			put("Italian BMT", 183);
			put("Italian Bread", 271);
			put("Italian Cheese", 397);
			put("Italian Dressing", 293);
			put("Italian Sausage", 149);
			put("Jack Daniel’s", 146);
			put("Jackfruit", 95);
			put("Jackfruit", 95);
			put("Jagermeister", 250);
			put("Jaggery", 383);
			put("Jalapeno", 13);
			put("Jambalaya", 100);
			put("Japanese Sweet Potatoes", 87);
			put("Jarlsberg", 352);
			put("Jelly Beans", 354);
			put("Jelly Belly", 354);
			put("Jelly", 278);
			put("Jerky", 410);
			put("Jif Peanut Butter", 580);
			put("Jim Beam", 222);
			put("Jolly Ranchers", 385);
			put("Jolt Cola", 44);
			put("Jordan Almonds", 429);
			put("Jujube", 79);
			put("Juniper", 45);
			put("Just Right", 391);
			put("Kahlua", 180);
			put("Kale", 49);
			put("Kamut", 337);
			put("Karamalz", 37);
			put("Kashi", 377);
			put("Kebab", 215);
			put("Kefir", 55);
			put("Kelloggs Corn Flakes", 357);
			put("Ketchup", 100);
			put("Key Lime Pie", 359);
			put("Keystone Ice", 40);
			put("Keystone Light", 29);
			put("Kidney Beans", 337);
			put("Kielbasa", 309);
			put("King Cake", 377);
			put("Kipper", 217);
			put("Kit Kat", 521);
			put("Kiwi", 61);
			put("Kiwi", 61);
			put("Kix", 367);
			put("Knackwurst", 307);
			put("Koelsch", 43);
			put("Kohlrabi", 27);
			put("Kombucha", 13);
			put("Kool-Aid", 26);
			put("Kool-Aid", 26);
			put("Krave", 372);
			put("Kumara", 86);
			put("Kumquat", 71);
			put("Labatt", 43);
			put("Lactose-free Milk", 52);
			put("Lacy Swiss Cheese", 321);
			put("Laffy Taffy", 372);
			put("Lager Beer", 43);
			put("Lamb Meat", 202);
			put("Lamb", 202);
			put("Land Shark", 42);
			put("Landjaeger", 352);
			put("Lard", 898);
			put("Lard", 902);
			put("Lasagna", 132);
			put("Lasagne Sheets", 271);
			put("Lasagne", 132);
			put("Lassi", 104);
			put("Lassi", 75);
			put("Latkes", 189);
			put("Latte Macchiato", 57);
			put("Layer Cake", 402);
			put("Leek", 61);
			put("Leerdammer Cheese", 284);
			put("Leerdammer", 284);
			put("Lemon Cake", 352);
			put("Lemon Grass", 99);
			put("Lemon Juice", 21);
			put("Lemon Meringue Pie", 268);
			put("Lemon Pie Filling", 143);
			put("Lemon", 29);
			put("Lemonade", 42);
			put("Lemonade", 42);
			put("Lemonade", 50);
			put("Lentil Soup", 56);
			put("Lentils", 353);
			put("Lettuce", 15);
			put("Licorice", 375);
			put("Licorice", 375);
			put("Life Cereal", 375);
			put("LifeSavers", 500);
			put("Light Beer", 29);
			put("Lima Beans", 71);
			put("Lima Beans", 71);
			put("Lime Juice", 21);
			put("Lime", 30);
			put("Limeade", 128);
			put("Lindt Chocolate", 548);
			put("Ling", 109);
			put("Linguica", 282);
			put("Linguine", 357);
			put("Linseed Oil", 837);
			put("Liqueur", 250);
			put("Liquor", 250);
			put("Liquorice", 375);
			put("Liver Pate", 319);
			put("Liverwurst", 305);
			put("Liverwurst", 326);
			put("Liverwurst", 326);
			put("Lobster Bisque Soup", 100);
			put("Lobster", 89);
			put("Lollipop", 392);
			put("Lotus Seed", 89);
			put("Low Carb Pasta", 282);
			put("Low-Fat Yogurt", 63);
			put("Lowenbrau", 45);
			put("Lucky Charms", 406);
			put("Luncheon Meat", 117);
			put("Lychee", 66);
			put("Lychees", 66);
			put("M&M’s", 479);
			put("Maasdam Cheese", 344);
			put("Maasdam Cheese", 344);
			put("Mac and Cheese", 370);
			put("Macadamia Nuts", 718);
			put("Macadamia Oil", 819);
			put("Macaroni and Cheese", 370);
			put("Macaroni", 370);
			put("Mackerel", 262);
			put("Madeira Cake", 394);
			put("Maggi", 104);
			put("Magnolia", 230);
			put("Magnum Almond", 315);
			put("Magnum Double Caramel", 355);
			put("Magnum Double Chocolate", 380);
			put("Magnum Gold", 341);
			put("Magnum White", 297);
			put("Magnum", 300);
			put("Malbec Wine", 82);
			put("Malbec", 82);
			put("Mallard Duck Meat", 211);
			put("Mallard Meat", 211);
			put("Malt Beer", 37);
			put("Malt Beer", 37);
			put("Malt Powder", 361);
			put("Malt-O-Meal", 51);
			put("Malted Milk", 405);
			put("Maltesers", 498);
			put("Maltitol", 210);
			put("Maltodextrin", 375);
			put("Maltose", 344);
			put("Manchego Cheese", 320);
			put("Mandarin Oranges", 53);
			put("Mandarin Oranges", 53);
			put("Mango Lassi", 66);
			put("Mango", 60);
			put("Mango", 60);
			put("Mangosteen", 73);
			put("Manicotti", 357);
			put("Maple Syrup", 270);
			put("Maracuya", 97);
			put("Maraschino Cherries", 165);
			put("Marble Cake", 339);
			put("Margarine", 717);
			put("Margarine", 717);
			put("Margherita Pizza", 275);
			put("Marjoram", 271);
			put("Marmite", 225);
			put("Marron", 210);
			put("Marrow Dumplings", 424);
			put("Mars Bar", 448);
			put("Marsala Wine", 100);
			put("Marshmallow Fluff", 666);
			put("Marshmallows", 318);
			put("Marzipan", 411);
			put("Mascarpone", 450);
			put("Mashed Potatoes", 83);
			put("Mashed Potatoes", 89);
			put("Matzo Bread", 351);
			put("Mayonnaise", 692);
			put("McDonald’s Big Mac", 256);
			put("McDonald’s Cheeseburger", 263);
			put("McDonald’s Chicken Nuggets", 297);
			put("McDonald’s Double Cheeseburger", 282);
			put("McDonald’s Filet-o-Fish", 275);
			put("McDonald’s McChicken", 251);
			put("McDonald’s McDouble", 252);
			put("McDonald’s McMuffi Egg", 225);
			put("McDonald’s McRib", 265);
			put("McDonald’s Mighty Wings", 308);
			put("McFlurry Oreo", 186);
			put("McFlurry", 153);
			put("McRib", 265);
			put("Meat Pie", 242);
			put("Meatball Sandwich", 161);
			put("Meatball Soup", 49);
			put("Meatloaf", 254);
			put("Meatloaf", 89);
			put("Mello Yello", 49);
			put("Menhaden Oil", 911);
			put("Meringue", 285);
			put("Merlot Wine", 83);
			put("Merlot", 83);
			put("Mettwurst", 310);
			put("Michelob Amber Bock", 47);
			put("Michelob Lager", 44);
			put("Michelob Light", 32);
			put("Michelob Ultra Amber", 26);
			put("Michelob Ultra Lime Cactus", 27);
			put("Michelob Ultra", 27);
			put("Midori", 267);
			put("Mike and Ike", 360);
			put("Milk Duds", 422);
			put("Milk", 61);
			put("Milk", 61);
			put("Milkfish", 190);
			put("Milkshake (dry)", 329);
			put("Milky Way", 449);
			put("Miller Chill", 31);
			put("Miller Genuine Draft", 40);
			put("Miller High Life Light", 31);
			put("Miller High Life", 40);
			put("Miller Lite", 27);
			put("Millet Flour", 372);
			put("Millet Gruel", 46);
			put("Millet", 378);
			put("Milo", 409);
			put("Milwaukee’s Best Light", 28);
			put("Milwaukee’s Best", 36);
			put("Minced Onion", 40);
			put("Minced Veal", 143);
			put("Minestrone", 34);
			put("Mini Milk", 120);
			put("Mini-Wheats", 353);
			put("Minneola", 64);
			put("Mint Chocolate Chip Ice Cream", 239);
			put("Mint", 70);
			put("Minute Maid Light", 2);
			put("Minute Maid", 46);
			put("Miso", 199);
			put("Mocca Yogurt", 100);
			put("Molasses", 290);
			put("Molson", 42);
			put("Monkey Bread", 290);
			put("Monkfish", 97);
			put("Monterey Jack Cheese", 373);
			put("Monterey Jack Cheese", 373);
			put("Monterey", 373);
			put("Moose Meat", 134);
			put("Moose", 134);
			put("Mortadella", 311);
			put("Moscato Wine", 76);
			put("Mostaccioli", 184);
			put("Mozzarella Pizza", 249);
			put("Mozzarella", 280);
			put("Mozzarella", 280);
			put("Muenster Cheese", 368);
			put("Muenster Cheese", 368);
			put("Muesli", 336);
			put("Muffin", 296);
			put("Mug Root Beer", 42);
			put("Mulberries", 43);
			put("Mulled Wine", 196);
			put("Mullet", 150);
			put("Multi-Grain Bread", 265);
			put("Multigrain Cheerios", 380);
			put("Mung Beans", 12);
			put("Mushroom Pizza", 212);
			put("Mushroom Soup", 35);
			put("Mushrooms", 22);
			put("Muskmelon", 34);
			put("Mussel", 172);
			put("Mustard Greens", 27);
			put("Mustard Oil", 884);
			put("Mustard Oil", 884);
			put("Mustard Sauce", 645);
			put("Mustard Seed", 508);
			put("Mustard", 60);
			put("Mutton Meat", 234);
			put("Mutton", 234);
			put("Naan", 275);
			put("Naan", 310);
			put("Nachos with Cheese", 306);
			put("Napoli Pizza", 202);
			put("Natto", 212);
			put("Natural Ice", 44);
			put("Natural Light", 27);
			put("Navy Bean", 337);
			put("Nectar", 53);
			put("Nectarine", 44);
			put("Nestea", 21);
			put("Nestea", 36);
			put("Neufchatel", 253);
			put("New York Strip Steak", 199);
			put("New York Style Pizza", 169);
			put("Newcastle", 39);
			put("Non-alcoholic Beer", 37);
			put("Non-alcoholic Beer", 37);
			put("Noni", 53);
			put("Nonpareils", 475);
			put("Noodle Soup", 34);
			put("Nori", 35);
			put("Norland Red Potatoes", 89);
			put("Nutella", 544);
			put("Nutmeg", 525);
			put("Nutri-Grain", 351);
			put("Oat Bran", 246);
			put("Oat Oil", 884);
			put("Oatibix", 421);
			put("Oatmeal Cookies", 450);
			put("Oatmeal Raisin Cookies", 435);
			put("Oatmeal", 375);
			put("Obatzda", 303);
			put("Octopus", 164);
			put("Okara", 77);
			put("Okra", 33);
			put("Okra", 33);
			put("Okra", 33);
			put("Old Milwaukee N.A.", 16);
			put("Old Milwaukee", 41);
			put("Olde English", 45);
			put("Olive Cream Cheese", 342);
			put("Olive Loaf", 232);
			put("Olive Oil", 800);
			put("Olive Oil", 884);
			put("Olive Spread", 550);
			put("Olives", 115);
			put("Olives", 115);
			put("Omelette", 154);
			put("Onion Powder", 341);
			put("Onion Rings", 411);
			put("Onion Soup", 23);
			put("Onion", 40);
			put("Onion", 40);
			put("Opera Cake", 320);
			put("Orange Chicken", 259);
			put("Orange Juice", 46);
			put("Orange Peel", 97);
			put("Orange Sauce", 179);
			put("Orange Soda", 48);
			put("Orange", 47);
			put("Orecchiette", 370);
			put("Oregano", 265);
			put("Organic Yogurt", 75);
			put("Orzo", 357);
			put("Ostrich Meat", 145);
			put("Ostrich Meat", 175);
			put("Ostrich", 145);
			put("Ostrich", 145);
			put("Ostrich", 175);
			put("Oven-Roasted Turkey Breast", 104);
			put("Oxtail Soup", 28);
			put("O’Doul’s (N.A.)", 19);
			put("Pabst Blue Ribbon", 41);
			put("Paczki", 336);
			put("Pad Thai", 150);
			put("Paella", 156);
			put("Pale Ale", 42);
			put("Palm Kernel Oil", 882);
			put("Palm Oil", 882);
			put("Palm Oil", 882);
			put("Pan de Sal", 293);
			put("Pancake", 227);
			put("Pancake", 233);
			put("Pandesal", 293);
			put("Panettone", 318);
			put("Panettone", 360);
			put("Papaya Juice", 58);
			put("Papaya", 43);
			put("Paprika", 282);
			put("Paratha", 325);
			put("Parma Ham", 261);
			put("Parma Ham", 345);
			put("Parmesan", 431);
			put("Parsley", 36);
			put("Parsnip", 75);
			put("Parsnips", 75);
			put("Passion Fruit Juice", 48);
			put("Passion Fruit", 97);
			put("Passion Fruit", 97);
			put("Pastrami", 133);
			put("Pastrami", 133);
			put("Pavlova", 294);
			put("PayDay", 462);
			put("Pea Soup", 75);
			put("Pea Soup", 75);
			put("Peach Cobbler", 65);
			put("Peach Juice", 54);
			put("Peach Nectar", 54);
			put("Peach Pie", 223);
			put("Peach Yogurt", 97);
			put("Peach", 39);
			put("Peanut Bar", 533);
			put("Peanut Brittle", 183);
			put("Peanut Butter Bars", 379);
			put("Peanut Butter Cookies", 475);
			put("Peanut Butter Sandwich", 408);
			put("Peanut Butter Toast Crunch", 431);
			put("Peanut Butter", 589);
			put("Peanut Oil", 857);
			put("Peanut Oil", 857);
			put("Peanuts", 567);
			put("Peanuts", 567);
			put("Pear Juice", 60);
			put("Pear Nectar", 60);
			put("Pear", 57);
			put("Pearl Barley", 352);
			put("Peas", 42);
			put("Peas", 81);
			put("Peas", 81);
			put("Pecan Nuts", 691);
			put("Pecan Pie", 407);
			put("Pecan", 691);
			put("Pecans", 691);
			put("Pecorino", 387);
			put("Peking Duck", 225);
			put("Penne Rigate", 370);
			put("Penne", 351);
			put("Pepper Cheese", 100);
			put("Pepper", 251);
			put("Pepper", 27);
			put("Peppermint Extract", 0);
			put("Peppermint bark", 500);
			put("Pepperoni Pizza", 255);
			put("Pepperoni", 494);
			put("Pepperoni", 494);
			put("Pepsi", 44);
			put("Persimmon", 127);
			put("Pesto Cream Cheese", 342);
			put("Pesto", 458);
			put("Peter Pan Peanut Butter", 609);
			put("Pez", 427);
			put("Pheasant Breast", 133);
			put("Pheasant Leg", 239);
			put("Pheasant Meat", 239);
			put("Pheasant", 239);
			put("Pheasant", 239);
			put("Philadelphia Cream Cheese", 342);
			put("Philadelphia Cream Cheese", 342);
			put("Philly Cheese Steak", 250);
			put("Physalis", 49);
			put("Pibb Xtra", 40);
			put("Pickerel", 111);
			put("Pickled Herring", 262);
			put("Pide", 268);
			put("Pie", 237);
			put("Pierogi", 200);
			put("Pig Brain", 138);
			put("Pig Ear", 166);
			put("Pig Fat", 638);
			put("Pig Heart", 148);
			put("Pig Kidney", 151);
			put("Pig Lung", 99);
			put("Pigeon", 142);
			put("Pig’s Tail", 396);
			put("Pig’s Trotter", 243);
			put("Pike", 113);
			put("Pili Nuts", 719);
			put("Pilsner", 43);
			put("Pimento Loaf", 265);
			put("Pine Nuts", 673);
			put("Pineapple Cream Cheese", 342);
			put("Pineapple Juice", 53);
			put("Pineapple Orange Juice", 50);
			put("Pineapple Upside-Down Cake", 319);
			put("Pineapple", 50);
			put("Pineapple", 50);
			put("Pink Grapefruit", 42);
			put("Pinot Gris", 83);
			put("Pinot Noir", 75);
			put("Pinto Beans", 347);
			put("Pinto Beans", 347);
			put("Pistachios", 562);
			put("Pita Bread", 275);
			put("Pizza Dough", 228);
			put("Pizza Hut Stuffed Crust Pizza", 255);
			put("Pizza Hut Supreme Pizza", 248);
			put("Pizza Rolls", 247);
			put("Pizza", 267);
			put("Plaice", 91);
			put("Plain Yogurt", 61);
			put("Plain Yogurt", 61);
			put("Plantain", 122);
			put("Plantains", 122);
			put("Plum Cake", 109);
			put("Plum Jam", 250);
			put("Plum Juice", 71);
			put("Plum Wine", 163);
			put("Plum", 46);
			put("Polenta", 366);
			put("Polish Sausage", 301);
			put("Pollack", 111);
			put("Pomegranate Juice", 66);
			put("Pomegranate", 83);
			put("Pomegranate", 83);
			put("Pomelo", 38);
			put("Pop Rocks", 358);
			put("Popcorn", 582);
			put("Poppy Seed Oil", 884);
			put("Poppy Seed", 525);
			put("Poppy Seeds", 525);
			put("Poppy Seeds", 525);
			put("Poppy-Seed Cake", 394);
			put("Pork Baby Back Ribs", 212);
			put("Pork Bacon", 407);
			put("Pork Belly", 518);
			put("Pork Blade Steak", 232);
			put("Pork Chop", 123);
			put("Pork Chop", 225);
			put("Pork Chops", 196);
			put("Pork Country-Style Ribs", 133);
			put("Pork Country-Style Ribs", 247);
			put("Pork Crown Roast", 212);
			put("Pork Cutlet", 131);
			put("Pork Cutlets", 131);
			put("Pork Leg", 201);
			put("Pork Liver", 165);
			put("Pork Loin", 143);
			put("Pork Loin", 204);
			put("Pork Meatloaf", 243);
			put("Pork Melt", 219);
			put("Pork Ragout", 73);
			put("Pork Rib Roast", 159);
			put("Pork Ribs", 292);
			put("Pork Roast", 194);
			put("Pork Roast", 247);
			put("Pork Roast", 254);
			put("Pork Roll", 302);
			put("Pork Sausage", 339);
			put("Pork Shank", 172);
			put("Pork Shoulder Blade", 232);
			put("Pork Shoulder", 269);
			put("Pork Steaks", 196);
			put("Pork Stomach", 250);
			put("Pork Tongue", 271);
			put("Pork", 196);
			put("Pork", 247);
			put("Port Wine", 160);
			put("Porter", 54);
			put("Porterhouse Steak", 247);
			put("Post Raisin Bran", 322);
			put("Post Shredded Wheat", 347);
			put("Potato Bread", 266);
			put("Potato Dumpling", 124);
			put("Potato Fritter", 185);
			put("Potato Gratin", 132);
			put("Potato Pancakes", 268);
			put("Potato Salad", 143);
			put("Potato Salad", 143);
			put("Potato Soup", 80);
			put("Potato Starch", 331);
			put("Potato Sticks", 522);
			put("Potato Waffles", 167);
			put("Potato Wedges", 123);
			put("Potato", 77);
			put("Potato", 77);
			put("Potatoes au Gratin", 132);
			put("Poularde", 200);
			put("Poultry Seasoning", 307);
			put("Pound Cake", 390);
			put("Poutine", 227);
			put("Powdered Milk", 496);
			put("Powdered Milk", 496);
			put("Powdered Sugar", 389);
			put("Powerade", 120);
			put("Powerade", 16);
			put("Prawn Crackers", 527);
			put("Pretzel Roll", 338);
			put("Pretzel Sticks", 380);
			put("Pretzel", 338);
			put("Prickly Pear", 41);
			put("Probiotic Yogurt", 80);
			put("Profiterole", 334);
			put("Prosciutto", 195);
			put("Prosciutto", 195);
			put("Prosecco", 66);
			put("Prosecco", 71);
			put("Protein Powder", 411);
			put("Provolone", 351);
			put("Puff Pastry", 558);
			put("Puff Pastry", 558);
			put("Puff", 367);
			put("Puffed Rice", 383);
			put("Puffed Wheat", 367);
			put("Pulled Pork Sandwich", 211);
			put("Pumpernickel", 250);
			put("Pumpkin Bread", 298);
			put("Pumpkin Cheesecake", 340);
			put("Pumpkin Pie Spice", 342);
			put("Pumpkin Pie", 243);
			put("Pumpkin Seed Oil", 880);
			put("Pumpkin Seeds", 559);
			put("Pumpkin Seeds", 560);
			put("Pumpkin Soup", 29);
			put("Pumpkin", 26);
			put("Punch", 62);
			put("Purple Majesty Potatoes", 72);
			put("Puy Lentils", 345);
			put("Pâté (720), Pate", 319);
			put("Quail Breast", 123);
			put("Quail", 227);
			put("Quaker Grits", 344);
			put("Quaker Oatmeal Squares", 400);
			put("Quaker Oatmeal", 375);
			put("Quark", 145);
			put("Quattro Formaggi Pizza", 248);
			put("Quince", 57);
			put("Quinoa", 368);
			put("Rabbit", 197);
			put("Rack of Pork", 241);
			put("Raclette Cheese", 357);
			put("Racoon Meat", 255);
			put("Racoon", 255);
			put("Radish Seeds", 43);
			put("Radishes", 16);
			put("Raisin Bran Crunch", 355);
			put("Raisin Bran Crunch", 355);
			put("Raisin Bran", 322);
			put("Raisin Bread", 274);
			put("Raisin Nut Bran", 367);
			put("Raisins", 299);
			put("Raisins", 474);
			put("Rajma", 140);
			put("Rambutan", 82);
			put("Rambutan", 82);
			put("Ramen", 436);
			put("Ramen", 447);
			put("Ranch Dressing", 510);
			put("Raspberries", 52);
			put("Raspberry Pie", 240);
			put("Ravioli", 203);
			put("Ravioli", 77);
			put("Ready Brek", 359);
			put("Real Butter", 720);
			put("Red Beans", 124);
			put("Red Cabbage", 31);
			put("Red Gold Potatoes", 89);
			put("Red Kidney Bean", 337);
			put("Red Lentils", 329);
			put("Red Pepper Pizza", 192);
			put("Red Pepper", 251);
			put("Red Potatoes", 89);
			put("Red Snapper", 128);
			put("Red Velvet Cake", 367);
			put("Red Wine Vinegar", 19);
			put("Red Wine", 85);
			put("Red Wine", 85);
			put("Red Wines", 85);
			put("Redbridge (Gluten-free)", 45);
			put("Redfish", 94);
			put("Reeses Peanut Butter Cups", 536);
			put("Refried Beans", 91);
			put("Reindeer Meat", 200);
			put("Reindeer", 200);
			put("Remoulade Sauce", 635);
			put("Reuben Sandwich", 208);
			put("Rhea", 160);
			put("Rhubarb Pie", 245);
			put("Rhubarb", 21);
			put("Rib Eye Steak", 217);
			put("Rice Bran Oil", 889);
			put("Rice Bran Oil", 889);
			put("Rice Chex", 387);
			put("Rice Krispies", 394);
			put("Rice Milk", 49);
			put("Rice Milk", 49);
			put("Rice Pudding", 118);
			put("Rice Pudding", 134);
			put("Ricotta", 174);
			put("Riesling Wine", 80);
			put("Riesling", 80);
			put("Rigatoni", 353);
			put("Ring Bologna", 286);
			put("Roast Beef", 111);
			put("Roast Beef", 140);
			put("Roast Beef", 187);
			put("Roast Beef", 267);
			put("Roast Dinner", 198);
			put("Roast Potatoes", 149);
			put("Roasted Almonds", 452);
			put("Roasted Soybeans", 471);
			put("Rock Sugar", 625);
			put("Rocky Road Ice Cream", 257);
			put("Roll", 316);
			put("Rolled Oats", 384);
			put("Rolling Rock Light", 30);
			put("Rolling Rock", 37);
			put("Rollmops", 171);
			put("Rolo", 474);
			put("Romano", 387);
			put("Root Beer", 41);
			put("Roquefort", 369);
			put("Rose Wine", 71);
			put("Rose Wine", 71);
			put("Rosemary Potatoes", 93);
			put("Rosemary", 131);
			put("Roti", 264);
			put("Rotini", 353);
			put("Round Steak", 182);
			put("Rum Cake", 351);
			put("Rum", 231);
			put("Rum", 246);
			put("Rump Steak", 171);
			put("Rusk", 410);
			put("Russet Potatoes", 97);
			put("Russian Banana Potatoes", 67);
			put("Russian Dressing", 400);
			put("Rutabaga", 38);
			put("Rye Bran", 281);
			put("Rye Bread", 259);
			put("Rösti", 138);
			put("Sacher Torte", 352);
			put("Safflower Oil", 857);
			put("Safflower Oil", 857);
			put("Safflower Seeds", 517);
			put("Saffron", 310);
			put("Sage", 315);
			put("Sago", 354);
			put("Salad Dressing", 449);
			put("Salami Pizza", 255);
			put("Salami", 336);
			put("Salami", 336);
			put("Salmon Cream Cheese", 342);
			put("Salmon Oil", 911);
			put("Salmon", 206);
			put("Salt Meat", 286);
			put("Salt Pork", 286);
			put("Salt", 0);
			put("Salted Butter", 717);
			put("Sambal Oelek", 21);
			put("Sambuca", 333);
			put("Samosa", 214);
			put("Samuel Adams", 45);
			put("Sandwich Bread", 251);
			put("Sandwich Cheese", 148);
			put("Sandwich", 304);
			put("Sangria", 132);
			put("Sangria", 96);
			put("Sapodilla", 83);
			put("Sardine Oil", 902);
			put("Sardines", 208);
			put("Sauerkraut Juice", 14);
			put("Sausage Pizza", 246);
			put("Sausage Roll", 350);
			put("Sausage Rolls", 297);
			put("Sausage", 230);
			put("Sauvignon Blanc", 81);
			put("Savory", 272);
			put("Savoury Biscuits", 347);
			put("Scallops", 111);
			put("Scampi", 84);
			put("Schnitzel", 156);
			put("Schwan’s", 246);
			put("Schweppes Ginger Ale", 38);
			put("Scone", 362);
			put("Scooters", 367);
			put("Scotch Broth", 33);
			put("Scotch", 222);
			put("Sea Bass", 124);
			put("Sea Salt", 0);
			put("Seafood Pizza", 245);
			put("Semi-skimmed Milk", 50);
			put("Semolina Flour", 350);
			put("Semolina Pudding", 67);
			put("Semolina", 340);
			put("Serrano Ham", 300);
			put("Serrano Ham", 339);
			put("Serrano Pepper", 32);
			put("Sesame Ginger Dressing", 464);
			put("Sesame Oil", 884);
			put("Sesame Oil", 889);
			put("Sesame Paste", 595);
			put("Sesame Seeds", 573);
			put("Sesame Seeds", 573);
			put("Sesame Seeds", 573);
			put("Shad", 252);
			put("Shallots", 72);
			put("Shark", 130);
			put("Shea Oil", 884);
			put("Sheep Cheese", 364);
			put("Shells", 353);
			put("Shepherds Pie", 70);
			put("Sherry", 116);
			put("Sherry", 116);
			put("Shirataki Noodles", 18);
			put("Shiraz", 71);
			put("Shock Top Raspberry Wheat", 50);
			put("Shock Top", 47);
			put("Shortbread", 502);
			put("Shortcrust Pastry", 544);
			put("Shredded Coconut", 501);
			put("Shredded Wheat", 340);
			put("Shreddies", 351);
			put("Shrimp Cocktail", 464);
			put("Shrimp Pizza", 209);
			put("Sicilian Pizza", 241);
			put("Sierra Nevada Strong", 62);
			put("Silken Tofu", 55);
			put("Skim Milk Yogurt", 56);
			put("Skim Milk", 35);
			put("Skippy Peanut Butter", 594);
			put("Skirt Steak", 205);
			put("Skittles", 405);
			put("Sloe Gin", 332);
			put("Sloppy Joe", 71);
			put("Sloppy Joes", 154);
			put("Slurpee", 4);
			put("Slush Puppie", 50);
			put("Smart Start", 371);
			put("Smarties McFlurry", 198);
			put("Smarties", 357);
			put("Smelt", 124);
			put("Smoked Almonds", 575);
			put("Smoked Cheese", 410);
			put("Smoked Ham", 107);
			put("Smoked Salmon", 158);
			put("Smoked Sausage", 301);
			put("Smoked Turkey Breast", 104);
			put("Smoothie", 37);
			put("Smores", 500);
			put("Smuckers Strawberry Jam", 250);
			put("Snickers Ice Cream", 360);
			put("Snickers", 484);
			put("Soda Bread", 290);
			put("Soda", 53);
			put("Soft Cheese", 268);
			put("Soft Serve", 222);
			put("Soft Tofu", 61);
			put("Sole", 86);
			put("Solero", 100);
			put("Sorbitol", 375);
			put("Soufflé", 204);
			put("Sour Cream Sauce", 60);
			put("Sour Cream", 181);
			put("Sour Cream", 217);
			put("Sour Patch Kids", 363);
			put("Sourdough Bread", 289);
			put("Soursop Fruit", 66);
			put("Souse", 157);
			put("Southern Comfort", 247);
			put("Soy Beans", 147);
			put("Soy Cheese", 235);
			put("Soy Mayonnaise", 322);
			put("Soy Milk", 41);
			put("Soy Milk", 45);
			put("Soy Milk", 45);
			put("Soy Noodles", 216);
			put("Soy Nut Butter", 562);
			put("Soy Nuts", 471);
			put("Soy Oil", 882);
			put("Soy Protein Powder", 338);
			put("Soy Sauce", 67);
			put("Soy Yogurt", 66);
			put("Soya Cheese", 235);
			put("Soybean Oil", 889);
			put("Soybeans", 147);
			put("Soynut Butter", 562);
			put("Spaetzle", 368);
			put("Spaghetti Bolognese", 132);
			put("Spaghetti", 370);
			put("Spam", 315);
			put("Spanakopita", 246);
			put("Spare Ribs", 238);
			put("Spare Ribs", 396);
			put("Spareribs", 238);
			put("Sparkling Wine", 190);
			put("Sparks", 74);
			put("Special K Chocolatey Delight", 388);
			put("Special K Protein Plus", 375);
			put("Special K Red Berries", 345);
			put("Special K", 377);
			put("Speculoos", 469);
			put("Spelt Bran", 177);
			put("Spelt Semolina", 360);
			put("Spelt", 338);
			put("Spice Cake", 332);
			put("Spicy Italian", 219);
			put("Spinach Feta Pizza", 242);
			put("Spinach Pizza", 234);
			put("Spinach Tortellini", 314);
			put("Spinach", 23);
			put("Spirelli", 367);
			put("Sponge Cake", 289);
			put("Spring Roll", 250);
			put("Spring Rolls", 250);
			put("Sprinkles", 500);
			put("Sprite Zero", 0);
			put("Sprite", 37);
			put("Spritz Cookies", 500);
			put("Squash", 45);
			put("Squid", 92);
			put("Squirrel Meat", 173);
			put("Squirrel", 173);
			put("Squirt", 44);
			put("St. Pauli Girl", 42);
			put("Standing Rib Roast", 333);
			put("Star Fruit", 31);
			put("Starch", 381);
			put("Starfruit", 31);
			put("Steel Reserve", 63);
			put("Stevia", 0);
			put("Stew Beef", 191);
			put("Stilton Cheese", 393);
			put("Stout Beer", 51);
			put("Stout", 51);
			put("Stracciatella Yogurt", 139);
			put("Strawberries", 32);
			put("Strawberry Cheesecake", 327);
			put("Strawberry Ice Cream", 236);
			put("Strawberry Jam", 250);
			put("Strawberry Jelly", 250);
			put("Strawberry Milkshake", 113);
			put("Strawberry Pie", 230);
			put("Strawberry Preserves", 278);
			put("Strawberry Rhubarb Pie", 281);
			put("Strawberry Sundae", 158);
			put("Strawberry Yogurt", 100);
			put("String Cheese", 250);
			put("Strip Steak", 117);
			put("Strong Beer", 55);
			put("Stuffed Crust Pizza", 255);
			put("Sturgeon", 135);
			put("Subway Club Sandwich", 131);
			put("Succotash", 115);
			put("Sucrose", 387);
			put("Sugar Peas", 42);
			put("Sugar Puffs", 379);
			put("Sugar", 405);
			put("Summer Sausage", 298);
			put("Sunbutter", 617);
			put("Sundae", 215);
			put("Sunflower Butter", 617);
			put("Sunflower Oil", 884);
			put("Sunflower Oil", 884);
			put("Sunflower Seeds", 117);
			put("Sunflower Seeds", 584);
			put("Sunflower Seeds", 584);
			put("Sunkist", 25);
			put("Surge", 48);
			put("Sushi", 150);
			put("Sweet Chestnut", 194);
			put("Sweet Peas", 48);
			put("Sweet Potato Pie", 260);
			put("Sweet Potato", 86);
			put("Sweet Potato", 92);
			put("Sweet Red Wine", 81);
			put("Sweet Rolls", 333);
			put("Sweet White Wine", 82);
			put("Sweet Wines", 83);
			put("Sweet and Sour Sauce", 179);
			put("Sweetened Condensed Milk", 321);
			put("Sweetened Condensed Milk", 321);
			put("Sweetener", 360);
			put("Swiss Cheese", 380);
			put("Swiss Roll", 313);
			put("Swiss Roll", 439);
			put("Swordfish", 172);
			put("S’mores", 500);
			put("T-Bone Steak", 202);
			put("T-Bone-Steak", 221);
			put("TaB", 0);
			put("Tabasco", 70);
			put("Taco", 217);
			put("Tagliatelle", 370);
			put("Take 5", 476);
			put("Tamarind", 239);
			put("Tamarind", 239);
			put("Tamarind", 239);
			put("Tandoori Chicken", 113);
			put("Tang", 381);
			put("Tangerine Juice", 43);
			put("Tangerine", 53);
			put("Tap Water", 0);
			put("Tapenade", 233);
			put("Taro", 112);
			put("Tarragon", 295);
			put("Tarte Flambée", 253);
			put("Tarte Tatin", 210);
			put("Tea", 1);
			put("Tempeh", 193);
			put("Tequila", 110);
			put("Teriyaki Sauce", 89);
			put("Textured Soy Protein", 571);
			put("Textured Vegetable Protein", 333);
			put("Thai Curry Paste", 155);
			put("Thai Soup", 60);
			put("Thin Crust Pizza", 261);
			put("Thyme", 276);
			put("Tilsit", 340);
			put("Tilt", 64);
			put("Tiramisu Cake", 291);
			put("Tiramisu", 283);
			put("Toast", 261);
			put("Toasties", 361);
			put("Toblerone", 525);
			put("Tofu", 76);
			put("Tomato Juice", 17);
			put("Tomato Paste", 82);
			put("Tomato Puree", 38);
			put("Tomato Rice Soup", 47);
			put("Tomato Sauce", 24);
			put("Tomato Seed Oil", 884);
			put("Tomato Soup", 30);
			put("Tomato", 18);
			put("Tongue", 284);
			put("Tonic Water", 35);
			put("Tortellini", 291);
			put("Tortilla Bread", 265);
			put("Tortilla Chips", 499);
			put("Tortilla Wrap", 271);
			put("Tortilla", 237);
			put("Tortilla", 297);
			put("Treacle Tart", 369);
			put("Tres Leches Cake", 246);
			put("Trifle", 180);
			put("Trifle", 186);
			put("Triggerfish", 93);
			put("Triple Sec", 153);
			put("Trix", 400);
			put("Trout", 190);
			put("Tuna Pizza", 254);
			put("Tuna Salad", 187);
			put("Tuna", 132);
			put("Tuna", 86);
			put("Turbot", 122);
			put("Turkey Breast", 104);
			put("Turkey Breast", 135);
			put("Turkey Breast", 135);
			put("Turkey Cutlet", 189);
			put("Turkey Drumsticks", 208);
			put("Turkey Giblets", 173);
			put("Turkey Ham", 126);
			put("Turkey Heart", 174);
			put("Turkey Hill", 271);
			put("Turkey Legs", 208);
			put("Turkey Legs", 208);
			put("Turkey Liver", 189);
			put("Turkey Salami", 152);
			put("Turkey Steak", 189);
			put("Turkey Steak", 189);
			put("Turkey Stomach", 148);
			put("Turkey Wings", 221);
			put("Turkey Wings", 221);
			put("Turkey", 104);
			put("Turkey", 189);
			put("Turkey", 189);
			put("Turmeric", 354);
			put("Turnip Greens", 20);
			put("Turnips", 28);
			put("Twix", 495);
			put("Tzatziki", 117);
			put("Tzatziki", 94);
			put("Unsalted Butter", 717);
			put("Unsalted Butter", 717);
			put("Vanilla Bean", 250);
			put("Vanilla Coke", 45);
			put("Vanilla Cone", 162);
			put("Vanilla Extract", 288);
			put("Vanilla Extract", 288);
			put("Vanilla Ice Cream", 201);
			put("Vanilla Milkshake", 149);
			put("Vanilla Sugar", 357);
			put("Vanilla Yogurt", 101);
			put("Veal Breast", 282);
			put("Veal Heart", 186);
			put("Veal Kidney", 163);
			put("Veal Leg", 211);
			put("Veal Roast Beef", 175);
			put("Veal Shank", 177);
			put("Veal Shoulder", 183);
			put("Veal Sirloin", 204);
			put("Veal Tenderloin", 217);
			put("Veal Tongue", 202);
			put("Veal", 282);
			put("Vegemite", 180);
			put("Vegetable Beef Soup", 31);
			put("Vegetable Broth", 5);
			put("Vegetable Cream Cheese", 342);
			put("Vegetable Juice", 21);
			put("Vegetable Oil", 800);
			put("Vegetable Oil", 884);
			put("Vegetable Pizza", 256);
			put("Vegetable Shortening", 884);
			put("Vegetable Soup", 28);
			put("Vegetable Stock", 5);
			put("Vegetarian Pizza", 256);
			put("Veggie Burger", 181);
			put("Veggie Delight", 138);
			put("Veggie Patty", 390);
			put("Veggie Pizza", 231);
			put("Venison Sirloin", 158);
			put("Venison", 164);
			put("Vermicelli", 368);
			put("Vermouth", 108);
			put("Vermouth", 130);
			put("Victoria Sponge Cake", 257);
			put("Vinaigrette", 120);
			put("Vinegar", 18);
			put("Vodka", 231);
			put("Volvic", 0);
			put("Waffles", 272);
			put("Waffles", 312);
			put("Wahoo", 167);
			put("Walnut Cream Cheese", 342);
			put("Walnut Oil", 889);
			put("Walnut Oil", 889);
			put("Walnuts", 131);
			put("Walnuts", 654);
			put("Wasabi", 109);
			put("Water", 0);
			put("Watermelon", 30);
			put("Watermelon", 30);
			put("Watermelon", 30);
			put("Wedding Cake", 381);
			put("Wedding Soup", 53);
			put("Weet-Bix", 353);
			put("Weetabix", 358);
			put("Weetos", 378);
			put("Weisswurst", 313);
			put("Wendy’s Baconator", 304);
			put("Wendy’s Jr. Bacon Cheeseburger", 261);
			put("Wendy’s Jr. Cheeseburger", 225);
			put("Wendy’s Son of Baconator", 321);
			put("Wheat Beer", 45);
			put("Wheat Bran", 216);
			put("Wheat Germ Oil", 929);
			put("Wheat Germ", 382);
			put("Wheat Gluten", 325);
			put("Wheat Semolina", 360);
			put("Wheat Starch", 351);
			put("Wheaties", 367);
			put("Whipped Cream", 257);
			put("Whisky", 250);
			put("White American", 148);
			put("White Beans", 336);
			put("White Bread", 238);
			put("White Cheddar", 403);
			put("White Cheddar", 403);
			put("White Grape Juice", 75);
			put("White Pepper", 296);
			put("White Pizza", 246);
			put("White Potatoes", 94);
			put("White Wine", 82);
			put("White Wine", 82);
			put("White Zinfandel", 88);
			put("Whitefish", 172);
			put("Whiting", 116);
			put("Whole Grain Noodles", 347);
			put("Whole Grain Spaghetti", 351);
			put("Whole Grain Wheat", 339);
			put("Whole Milk", 61);
			put("Whole Milk", 61);
			put("Whole Wheat Bread", 247);
			put("Whole Wheat Flour", 340);
			put("Wholegrain Oat", 375);
			put("Whoopie Pie", 400);
			put("Whopper", 231);
			put("Wild Boar Meat", 160);
			put("Wild Boar", 160);
			put("Wild Duck", 211);
			put("Wild Honey", 286);
			put("Wine", 83);
			put("Wine", 83);
			put("Winter Squash", 34);
			put("Wisconsin Cheese", 389);
			put("Worcestershire Sauce", 78);
			put("Xylitol", 240);
			put("Yam Bean", 38);
			put("Yam", 118);
			put("Yams", 116);
			put("Yeast (dry)", 325);
			put("Yellow Lentils", 304);
			put("Yellow Tail Wine", 71);
			put("Yerba Mate", 62);
			put("Yogurt Corner", 119);
			put("Yogurt Dressing", 45);
			put("Yogurt", 61);
			put("Yogurt", 61);
			put("Yoplait Boston Cream Pie", 90);
			put("Yoplait French Vanilla", 100);
			put("Yoplait Greek Blueberry", 100);
			put("Yoplait Greek Coconut", 100);
			put("Yoplait Greek Strawberry", 100);
			put("Yoplait Greek Vanilla", 100);
			put("Yoplait Harvest Peach", 100);
			put("Yoplait Key Lime Pie", 100);
			put("Yoplait Mango", 100);
			put("Yoplait Mixed Berry", 100);
			put("Yoplait Pina Colada", 100);
			put("Yoplait Strawberry Banana", 100);
			put("Yoplait Strawberry Cheesecake", 100);
			put("Yoplait Strawberry", 100);
			put("Yorkshire Pudding", 553);
			put("Young Gouda", 356);
			put("Yuba", 176);
			put("Yukon Gold Potatoes", 82);
			put("Zander", 84);
			put("Zesty Italian Dressing", 267);
			put("Zinfandel", 88);
			put("Zinger Burger", 256);
			put("Zinger", 256);
			put("Ziti", 352);
			put("Zucchini", 17);
		}};
		map.forEach((name, calories) -> addNewFood(name, calories));
	}

	public long findFoodData(String foodName, ArrayList<Food> allFood) {
		int maxSize = allFood.size();
		return 0;
	}

	//TODO - complete inventory

	// public static Inventory getInstance() {
	// }

	// public List<User> getListOfUsers() {
	// }

	// public List<TimeSlot> getWeekSchedule() {
	// }

	// public List<MindfulnessExercise> getAvailableMindfulnessExercises() {
	// }

	// public List<WorkoutExercises> getAvailableWorkoutExercises() {
	// }

	// public String getWorkoutDifficulty(int difficulty) {
	// }

	// public List<String> getTargetAttribute() {
	// 	return this.targetAttribute;
	// }

	// public boolean setWeekSchedule(List<TimeSlot> newWeekSchedule) {
	// }

	// public boolean setWorkoutDifficulties(List<String> newWorkoutDifficulties) {
	// }

	// public boolean setStatusList(List<String> newStatusList) {
	// }

	// public boolean setTargetTypes(List<String> newTargetTypes) {
	// }

	// public boolean setTargetProperties(List<String> newTargetProperties) {
	// }
}
